### ISSUE TITLE
Questions on SR Implementation and Intended Behavior

### ISSUE THREAD

**Issue by neng2** [Ascend-Research/Turtle#5]
Hello,

Thank you for providing this excellent work. I have been experimenting with the code, but I encountered some ambiguities that I wanted to clarify to ensure I understand the intended behavior correctly. Below are my questions:

**Input Data Format**

File: turtle_super_t1_arch.py
Function: forward
In the current implementation, what is the exact expected format for the input tensor? Should it be (B, n_sequence, C, H, W) as suggested by the forward function, or is it (B, C, H, W) or another format? Clarifying this would help avoid potential shape mismatches.
For example, I encountered the following error, which led me to modify the code as follows:
![image](https://github.com/user-attachments/assets/0e6888af-203f-44f3-805a-0f8745a3686a)
```

def forward(self, inp_img_, k_cached=None, v_cached=None):
        B, _, C, H, W = inp_img_.shape
        # print("inforward")
        # print(inp_img_.shape)
        inp_img_ = self.check_image_size(inp_img_)
        
        # print(inp_img_.shape)
        H, W = H*4, W*4 # scale factor
        if k_cached == None:
            k_cached = [None] * 8
            v_cached = [None] * 8

        k_to_cache = []
        v_to_cache = []
        # print(self.use_both_input)

        
        if self.use_both_input:
            previous, current = inp_img_[:, 0, :, :, :], inp_img_[:, 1, :, :, :]
            inp_img = torch.cat([previous, 
                                current], dim=1)
            
            inp_img = self.upsample_4x(inp_img)
            current = self.upsample_4x(current)
        else:
            inp_img = inp_img_[:, 1, :, :, :]
            
            inp_img = self.upsample_4x(inp_img)
            current = inp_img
```

I also tried modifying the check_image_size part forward and in a different way.

```
def check_image_size(self, x):
        _, _, _, h, w = x.size()
        # _, _, h, w = x.size()
        mod_pad_h = (self.padder_size - h % self.padder_size) % self.padder_size
        mod_pad_w = (self.padder_size - w % self.padder_size) % self.padder_size
        x = F.pad(x, (0, mod_pad_w, 0, mod_pad_h))
        return x
```
Here, I adjusted the line _, _, _, h, w = x.size() to _, _, h, w = x.size(). While this resolved the error, I am unsure if the changes align with the intended behavior (result) of the code.

**check_image_size Function Input**

File: turtle_super_t1_arch.py
Function: check_image_size
The check_image_size function seems to process a 4D tensor (B, C, H, W). Is this assumption correct, and is it guaranteed that all inputs to this function adhere to this shape throughout the pipeline?

**Super-resolution Upscaling Process**

_File: turtle_super_t1_arch.py
Function: forward_
In the current code, SR tasks appear to rely on self.upsample_4x. Is this the only intended upscaling step for SR tasks? How does this fit into the overall processing pipeline, and are there additional considerations to ensure SR quality?

**Tile-based Inference and Boundary Handling**

_File: inference_no_ground_truth.py
Function: run_inference_patched_
The run_inference_patched function performs tile-based inference, but it appears there is no explicit handling for blending or smoothing tile boundaries. Is the current E.div_(W) operation sufficient to ensure smooth boundary transitions, or is there a reason why blending logic is not included?

**Dataset-Specific Logic for MVSR**

_File: inference_no_ground_truth.py
Function: run_inference_patched_
The code includes a section for dataset_name == "MVSR", which applies downscaling and upscaling operations. Should similar logic be applied to other datasets, or is this process unique to MVSR? How does this impact SR performance for non-MVSR datasets?

**use_both_input Parameter**

_File: turtle_super_t1_arch.py
Function: forward_
The YML configuration uses use_both_input: False, suggesting single-frame inputs. However, for SR tasks, multi-frame inputs could be beneficial. Is single-frame input the intended behavior, or should use_both_input: True be used for better performance?

**torch.clamp and Tile Boundary Blending**

_File: inference_no_ground_truth.py
Function: run_inference_patched_
The torch.clamp operation after E.div_(W) seems to restrict output values to the range [0, 1]. Is this meant to improve tile boundary consistency, or is it purely for restricting output values? Is additional boundary smoothing unnecessary in this implementation?

**Quality of Results**

_File: General observation during experiments_
In my experiments, the output SR images appear to have significantly lower quality than expected. Are there specific configurations, settings, or additional steps required to achieve the optimal results?
Thank you for your time and support. I hope these questions help clarify my understanding and ensure I am following the intended pipeline correctly.

Looking forward to your guidance!

Best regards,
neng2

**Comment by Amirhosein-gh98** [comment]
Hi, 

Thank you for your interest in our work and for going through it in such detail. I appreciate the effort you’ve put into experimenting with the code and raising these important questions. Let me address them one by one:

### Input Data Format
Although we process the video frame by frame, the model accepts two frames as input. However, in all our experiments, we used use_both_input: False, effectively relying only on the second (current) frame. This option exists because, during initial experiments, we tested the effect of passing two frames to the model versus passing one frame and relying on the CHM (Causal History Module) to borrow information from past frames. You are welcome to enable use_both_input: True to concatenate the two frames and compare the results for your use case.

To clarify the input tensor format:
- By default, the input to the model is (B, 2, C, H, W), where 2 represents the two frames (previous and current).
- If use_both_input: True, the frames are concatenated along the channel dimension, resulting in an input tensor of shape (B, 2*C, H, W).
- If use_both_input: False, only the second frame (current) is used, resulting in a tensor of shape (B, C, H, W).

Regarding the check_image_size function: Since it operates on the tensor after this dimensional change, the modification you made is correct and aligns with the intended behavior.

---

### Super-Resolution Upscaling
We applied a simple upscaling scheme (self.upsample_4x) without extensive testing of configurations or exploring advanced upsampling methods. The primary purpose was to demonstrate the generalizability of our model to tasks like SR. 

Feel free to explore alternative upsampling schemes or configurations for improved results, and we'd be happy to hear about your findings.

---

### Tile-Based Inference and Boundary Handling
For tile-based inference, we rely on overlapping tiles, with the overlap amount determined by the tile_size and stride. In overlapping areas, we take the mean to ensure smooth transitions, a method commonly used in similar works like VRT and RVRT. 

That said, more sophisticated methods for blending or smoothing tile boundaries could further enhance the output quality. You are welcome to explore such techniques, and inference on full-sized images or increasing the overlap can also improve results.

---

### Dataset-Specific Logic for MVSR
The logic for dataset_name == "MVSR" was implemented because MVSR was the only SR dataset we experimented with. The same logic should generally apply to any other SR dataset. Feel free to modify the code for additional datasets and share your findings.

---

### torch.clamp and Boundary Smoothing
The torch.clamp operation ensures that output values are restricted to a valid range [0, 1] and is unrelated to boundary smoothing. If you have ideas or methods for smoothing tile boundaries, we encourage you to implement and test them. Let us know about your results, and we’d be happy to incorporate any improvements into the code.


Let me know if you have any other questions.

**Comment by neng2** [comment]
Hi,

Thank you so much for your kind and prompt response. Your reply helped me confirm that my modifications to the forward function align with your intended behavior. Additionally, it reassured me about the current boundary smoothing approach. Once I address some of the other issues I’m encountering, I hope to explore boundary smoothing further and share any improvements I discover.

That said, I would like to ask about a few other issues that remain unclear to me. Specifically, I’m still uncertain about the upscaling procedure in the code. Allow me to explain the flow as I understand it and highlight where I encountered issues.

**1. SR Workflow Without Patches (do_patches=False)**
In the Turtle project, the SR task begins with the following code snippet:

```
config = "./options/Turtle_SR_MVSR.yml"
    model_path = "./trained_models/SuperResolution.pth"
    model_name = "Turtle_SR"
    # print(model_name)
    
    with torch.no_grad():
        _, _ = main(model_path=model_path,
                    model_name=model_name, 
                    config_file=config,
                    data_dir="./dataset/", #Path to the desired video frames folder
                    model_type="SR", #simple_parallel(For big patches), simple

                    save_image=True,
                    image_out_path="./results",

                    do_pacthes=False,
                    tile=320,
                    tile_overlap=128)

    end = time.time()
    print(f"Completed in {end-st}s")
```

Here, when do_pacthes (which seems to be a typo for "patches") is set to False, the input image is not divided into tiles, and SR is performed on the whole frame.

The process then proceeds to this section of main:

```
_, _ = run_inference(video_name,
                                test_loader,
                                model,
                                device,
                                model_name,
                                save_img=save_image,
                                do_patched=do_pacthes,
                                image_out_path=image_out_path,
                                tile=tile,
                                tile_overlap=tile_overlap)
```
Since do_patched is False, the following code in run_inference is executed:

```
if do_patched:
            # do inference in patches, and concatenate before computing PSNR/SSIM.
            x2, k_cache, v_cache = run_inference_patched(
                                        previous_frame.unsqueeze(0),
                                        current_frame.unsqueeze(0),
                                        model, device, tile=tile, 
                                        tile_overlap=tile_overlap,
                                        prev_patch_dict_k=k_cache, 
                                        prev_patch_dict_v=v_cache)
        else:
            # do inference on whole frame if the memory can be fit.
            x = torch.concat((previous_frame.unsqueeze(0), 
                            current_frame.unsqueeze(0)), dim=0).to(device)
            x2, k_cache, v_cache = model(x.unsqueeze(0), k_cache, v_cache)
            x2 = torch.clamp(x2, 0, 1)
```

Here, the else branch is taken, and the model outputs 'x2'.
The model applies 4x upscaling in turtle_super_t1_arch, so for an input resolution of 320x180, the output is as follows:

output shape: torch.Size([1, 3, 720, 1280])

However, the subsequent lines of code:

```
x2 = x2.squeeze(0)
x2 = x2[:, :h, :w]
```
Use h and w values defined earlier in the script:

`c, h, w = current_frame.shape`
(156 line in inference_no_gorund_truth.py)


When saving an upscaled image, x2 is used to save it.
This causes the upscaled image to be resized back to the input frame’s original resolution when saved, producing the following output:

![Frame_1_Pred](https://github.com/user-attachments/assets/ddd9543f-77b1-4ae5-804e-c264430b05af)

Notably, when do_patches=False, the main function does not seem to properly account for upscaling.

**2. My Modification for Upscaling**
To address this, I modified the code as follows:
```
scale = 4
x2 = x2.squeeze(0)
x2 = x2[:, :h*scale, :w*scale]
```
With this change, I obtained an output with the correct 4x resolution:

input:
![00000000](https://github.com/user-attachments/assets/1d576a5d-f2b7-42ad-ab30-79135ab33259) 

output:
![Frame_1_Pred](https://github.com/user-attachments/assets/10f5e129-aa00-4fda-8233-dda2e2d283c0)

I used the REDS dataset for this experiment.

However, despite these modifications, the SR results still did not meet my expectations. This led me to suspect that my changes might not align with the intended behavior of the code.

This made me wonder:
> Super-Resolution Upscaling
> We applied a simple upscaling scheme (self.upsample_4x) without extensive testing of configurations or exploring advanced upsampling methods. The primary purpose was to demonstrate the generalizability of our model to tasks like SR.
> 
> Feel free to explore alternative upsampling schemes or configurations for improved results, and we'd be happy to hear about your findings.

Could this issue be related to the part you mentioned about upscaling and its purpose in demonstrating the model's generalizability?

**3. SR Workflow With Patches (do_patches=True)**

I encountered a similar question here as well when do_patches=True.
When do_patches=True, the following section of code is executed:

```
if do_patched:
            # do inference in patches, and concatenate before computing PSNR/SSIM.
            x2, k_cache, v_cache = run_inference_patched(
                                        previous_frame.unsqueeze(0),
                                        current_frame.unsqueeze(0),
                                        model, device, tile=tile, 
                                        tile_overlap=tile_overlap,
                                        prev_patch_dict_k=k_cache, 
                                        prev_patch_dict_v=v_cache)
```
This leads to the run_inference_patched method:

```
def run_inference_patched(img_lq_prev,
                          img_lq_curr,
                          model, device,
                          tile,
                          tile_overlap,
                          prev_patch_dict_k=None, 
                          prev_patch_dict_v=None,
                          img_multiple_of = 8,
                          scale=1):
```
Questions about run_inference_patched:
The scale argument is defined but never used. Additionally, unlike inference.py, this function does not take dataset_name as an argument. Why is this the case?


After this point, the sizes of H, W, padh, and padw are determined based on the given tile and tile_overlap. The determined tile coordinates are inserted into h_idx_list and w_idx_list, and a nested iteration is performed.

Here is a simplified diagram summarizing the flow as I understand it:

<img width="809" alt="image" src="https://github.com/user-attachments/assets/0e9b174c-f861-4174-aadb-31c511c03674">

When patches are processed, the following section scales them down by a factor of 1/4:
```
            in_patch_prev = torch.nn.functional.interpolate(in_patch_prev, 
                                                                    scale_factor=1/4,
                                                                    mode="bicubic")
            in_patch_curr = torch.nn.functional.interpolate(in_patch_curr, 
                                                                    scale_factor=1/4, 
                                                                    mode="bicubic")
```
Why are patches scaled down in this way? Without this step, a shape mismatch error occurs, but it’s unclear why scaling is necessary for SR.

If you add that without any other modifications and infer the result using the same data as when do_patches above is False,

![Frame_1_Pred](https://github.com/user-attachments/assets/60d7f989-4bfb-46a9-8f68-6b72a76e3bcb)

You get these results: If you zoom in and look closely, you can see that lines that appear as the boundaries of the tile are also visible.

**4. My Modifications for Patches**

Initially, I referenced the inference.py code and added the missing lines to improve the results. However, the results were similar to what I previously mentioned, so I attempted a different modification.
First, I tried utilizing the unused scale argument.

Without scaling down the size of the previous patch and current patch through interpolation, the following error occurs:

Traceback (most recent call last):
  File "/mnt/jhkang/Turtle/basicsr/inference_no_ground_truth.py", line 377, in <module>
    _, _ = main(model_path=model_path,
  File "/mnt/jhkang/Turtle/basicsr/inference_no_ground_truth.py", line 278, in main
    _, _ = run_inference(video_name,
  File "/mnt/jhkang/Turtle/basicsr/inference_no_ground_truth.py", line 175, in run_inference
    x2, k_cache, v_cache = run_inference_patched(
  File "/mnt/jhkang/Turtle/basicsr/inference_no_ground_truth.py", line 132, in run_inference_patched
    E[..., h_idx*scale:(h_idx+tile)*scale, w_idx*scale:(w_idx+tile)*scale].add_(out_patch)
RuntimeError: The size of tensor a (184) must match the size of tensor b (736) at non-singleton dimension 3

> _(I attached the results of the modified code. Here, the scale value was set to 1 and tested, so it works the same as the original code.)_

This raised the question:

Why does the implementation reduce the input scale for SR — a task specifically aimed at upscaling — instead of increasing the output scale directly?
Scaling down the input by 1/4, applying SR to upscale it by 4x, and then stitching the patches back together results in an output image of the same resolution as the input.

To address this, I modified the following lines in inference_no_ground_truth.py:

Line 81:
`E = torch.zeros(b, c, h*scale, w*scale).type_as(img_lq_curr)`
Lines 120-121:
```
E[..., h_idx*scale:(h_idx+tile)*scale, w_idx*scale:(w_idx+tile)*scale].add_(out_patch)
W[..., h_idx*scale:(h_idx+tile)*scale, w_idx*scale:(w_idx+tile)*scale].add_(out_patch_mask)
```
I also set the scale argument to 4.

Following this change, to ensure the final output image retains the correct resolution after exiting run_inference_patched, I made similar adjustments to the 'x2' slicing in the run_inference function:

```
        scale = 4
        x2 = x2.squeeze(0)
        x2 = x2[:, :h*scale, :w*scale]
```

After these modifications, I obtained the following output:
![Frame_1_Pred](https://github.com/user-attachments/assets/914005bc-bcc3-477a-b374-0d6860cf9ffb)

This result was generated with tile=320 and tile_overlap=128.

I also experimented with different values for tile and tile_overlap, which revealed other issues such as visible tile boundaries or even missing tiles in the final output.

I am unsure if my modifications align with the intended behavior or if there is a better way to achieve correct SR results that I might have missed.
Thank you for your patience and for taking the time to read this lengthy message. I appreciate your help!

Best regards,
neng2

**Comment by Amirhosein-gh98** [comment]
Thanks for going through our code in detail. As you mentioned, there were several issues with SR inference code, and we fixed all of them in the SR model and Inference codes. please clone the code again and run the latest version.

## 1. Scaling the Input

The MVSR4x dataset, used for real-world video super-resolution, is sourced from the EAVSR paper ([link to paper](https://openaccess.thecvf.com/content/CVPR2023W/NTIRE/papers/Wang_Benchmark_Dataset_and_Effective_Inter-Frame_Alignment_for_Real-World_Video_Super-Resolution_CVPRW_2023_paper.pdf)). The dataset is collected using two side-by-side cameras on a mobile phone: an ultra-wide camera and a telephoto camera. The low-quality frame is captured by the ultra-wide camera, while the high-quality frame comes from the telephoto camera. The focal length of the ultra-wide camera is 13mm, while the telephoto camera has a focal length of 90mm. 

By computing the ratio of these focal lengths (90/13), we find that the telephoto lens provides a zoom factor of 6.92 times more than the ultra-wide lens. However, for simplicity, the authors of the paper limit the zoom factor to 4x. 

When the dataset is downloaded, the frame pairs (one from each camera) have the same spatial resolution, but the ultra-wide frame is of noticeably lower quality than the telephoto frame. In the super-resolution task, the authors suggest manually downscaling the ultra-wide frame by a 4x factor to simulate the degraded input. This downscaling ensures that the ultra-wide frame mimics being 4x worse than the ground-truth telephoto frame, aligning with the real-world degradation.

This approach to super-resolution differs from typical SR tasks, where the degradation is often modeled synthetically using bicubic interpolation (BI) or bilinear downsampling (BD), as seen in tasks like REDS SR.

## 2. SR Workflow

During inference, the low-quality input frame (`img_lq`) is processed to match the resolution of the ground-truth frame (`img_gt`), since both frames share the same spatial resolution in the MVSR4x dataset. To simulate the degradation, the ultra-wide frame (`lq`) is manually downscaled using bicubic interpolation, as shown below:

```python
torch.nn.functional.interpolate(prev_frame, scale_factor=1/4, mode="bicubic")
torch.nn.functional.interpolate(current_frame, scale_factor=1/4, mode="bicubic")
```

So if the LQ data is already in lower spatial resolution than your desired output resolution, this downsampling step should be commented in the inference code.

## 3. Output Quality on REDS Dataset

The SR model was trained on the MVSR4x dataset, which, as explained earlier, is based on real-world degradation and differs from the synthetic SR tasks typically seen in datasets like REDS. To achieve optimal results for your specific task, you will need to train the SR model on the new dataset yourself. 

We will be adding a **Contributions** section to the README. If you retrain the model on a synthetic SR task and open a pull request with your code and trained model, we will be happy to merge your model into the codebase. Additionally, we will acknowledge your contribution in the README.


Thanks again for your interest in our work.
